# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e451bd8b7d3342b35cf1567732123536d9efd056aa8d8fe7570fa4bc627188c5ae590e8dbf2363642c81de295879509bc3788fcaa6ba2cb96ad343ca921dd5c

test:
  secret_key_base: 3e2804eec0072159e5a1a3bb71273830a8bbd0ad84cc14f928e60e82742246f9ef15e66599402aaa54d959368cea082d25d086d1d793030eed6b512c8b002f62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
